settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: real-estate
  path: /Users/abdullah/github/real-estate
  commands:
    vet:
      status: true
    install:
      status: true
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignore:
      paths:
      - .git
      - .realize
      - vendor
