version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go vet
      - run: fmt.Println("hello")
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
